AListFunc := TFunctionInstance.Create('BuiltIn', nil, nil, 'TListInstance', True);
AListType := TDataType.Create('TListInstance', 'List');
AListType.PMembers.Add('length', AListFunc);
AListType.PMembers.Add('set', AListFunc);
AListType.PMembers.Add('unpack', AListFunc);
AListType.PMembers.Add('pop', AListFunc);
AListType.PMembers.Add('prepend', AListFunc);
AListType.PMembers.Add('clear', AListFunc);
AListType.PMembers.Add('writeText', AListFunc);
AListType.PMembers.Add('append', AListFunc);
AListType.PMembers.Add('lock', AListFunc);
AListType.PMembers.Add('addLock', AListFunc);
AListType.PMembers.Add('changeLock', AListFunc);
AListType.PMembers.Add('path', AListFunc);
AActRec.AddMember('List', AListType);
