AListType := TBuiltInType.Create('TListInstance', 'List');
AListFunc := TFunctionInstance.Create('BuiltIn', nil, nil, 'TListInstance', True);
AListType.PMembers.Add('length', AListType);
AListType.PMembers.Add('set', AListType);
AListType.PMembers.Add('pop', AListType);
AListType.PMembers.Add('prepend', AListType);
AListType.PMembers.Add('clear', AListType);
AListType.PMembers.Add('writeText', AListType);
AListType.PMembers.Add('append', AListType);
AListType.PMembers.Add('lock', AListType);
AListType.PMembers.Add('addLock', AListType);
AListType.PMembers.Add('changeLock', AListType);
AActRec.AddMember('List', AListType);
