@url = http://localhost:3500
@posts = {{url}}/posts

###
GET {{posts}}

###
GET {{posts}}/99

###
POST {{posts}}/99

###
POST {{posts}}/99

###

GET {{posts}}/ui

###
POST {{url}}/posts/ui

###
GET {{url}}/posts/new

###
GET {{url}}/off

###
POST https://reqres.in/api/users
Content-Type: application/x-www-form-urlencoded

name=Zika&function=Topper&money=7000